name: LACI
favicon: null
layout_spectrum: 0.229
typography_spectrum: 0.23419
title: Los Angeles Cleantech Incubator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3125
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
