name: LACI
favicon: null
layout_spectrum: 0.35536169866099954
typography_spectrum: 0.25585093279369175
title: Los Angeles Cleantech Incubator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.40066350577399135
  lightness: 0.038641785737127066
  saturation: 0.024023402016609907
  rhythmicContrast: 0.6007213180419058
purpose: []
